services:
  frontend:
    image: AhmadHakim2004/quirknotes_frontend:latest
    build:
      context: .
      dockerfile: Dockerfile_frontend.dockerfile
      target: frontend
    ports:
      - "3000:3000"
    environment:
      - ENV=Docker

  backend:
    image: AhmadHakim2004/quirknotes_backend:latest
    build:
      context: .
      dockerfile: Dockerfile_backend.dockerfile
      target: backend
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb
 
  mongodb:
    image: mongo:latest 
    ports:
      - "27017:27017"